# Generated by Django 4.2.16 on 2024-11-26 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationInfo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('production_date', models.DateTimeField()),
                ('edition_date', models.DateTimeField(blank=True, null=True)),
                ('abstract', models.TextField()),
                ('spatial_rep_type', models.CharField(choices=[('RASTER', 'Raster'), ('VECTOR', 'Vector')], max_length=10)),
                ('equivalent_scale', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('geographic_bounding_box', models.JSONField(default=dict, help_text="Format: {'north': float, 'south': float, 'east': float, 'west': float}")),
                ('update_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.JSONField(db_index=True, default=list)),
                ('keyword_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('metadata_linkage', models.TextField(blank=True, null=True)),
                ('metadata_standard', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=10)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'role'], name='api_user_email_02c2d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResourceConstraints',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_constraints', models.TextField(blank=True, null=True)),
                ('use_constraints', models.TextField(blank=True, null=True)),
                ('other_constraints', models.TextField(blank=True, null=True)),
                ('identification_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='api.identificationinfo')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceSystem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reference_system', to='api.metadata')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointOfContact',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Enter phone number in international format: +1234567890', max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('role', models.CharField(max_length=255)),
                ('identification_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_of_contact', to='api.identificationinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetadataContact',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Enter phone number in international format: +1234567890', max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('role', models.CharField(max_length=255)),
                ('weblink', models.URLField(blank=True, null=True)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='api.metadata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='metadata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='api.user'),
        ),
        migrations.AddField(
            model_name='identificationinfo',
            name='metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='identification', to='api.metadata'),
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('weblink', models.URLField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=255, null=True)),
                ('distributor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order_process', models.TextField(blank=True, null=True)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribution', to='api.metadata')),
            ],
        ),
        migrations.CreateModel(
            name='DataQuality',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completeness_report', models.TextField(blank=True, null=True)),
                ('accuracy_report', models.TextField(blank=True, null=True)),
                ('process_description', models.TextField(blank=True, null=True)),
                ('process_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality', to='api.metadata')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemporalExtent',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('identification_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temporal_extent', to='api.identificationinfo')),
            ],
            options={
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='api_tempora_start_d_237dd1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResourceLineage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement', models.TextField()),
                ('hierarchy_level', models.PositiveIntegerField()),
                ('process_software', models.CharField(blank=True, max_length=255, null=True)),
                ('process_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lineage', to='api.metadata')),
            ],
            options={
                'indexes': [models.Index(fields=['hierarchy_level', 'process_date'], name='api_resourc_hierarc_3ed92f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='identificationinfo',
            index=models.Index(fields=['title', 'production_date'], name='api_identif_title_05ff2f_idx'),
        ),
        migrations.AddIndex(
            model_name='identificationinfo',
            index=models.Index(fields=['spatial_rep_type'], name='api_identif_spatial_788ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['name', 'format'], name='api_distrib_name_c75464_idx'),
        ),
    ]
